apiVersion: batch/v1
kind: Job
metadata:
  name: 666-biomedbert-none-fit
  labels:
    app: 666-biomedbert-none-fit
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: 666-biomedbert-none-fit
    spec:
      containers:
        - name: 666-biomedbert-none-fit
          image: registry.datexis.com/troehr/text_redact
          command: [ "python", "infrastructure/frameworks/task_model/task_main.py",
            "fit", 
            "--trainer.accelerator=gpu",
            "--trainer.devices=auto",
            "--trainer.precision=bf16-mixed",
            "--trainer.default_root_dir=/pvc/logs/biomedbert/666-biomedbert-none",
            "--trainer.callbacks+=EarlyStopping",
            "--trainer.callbacks.patience=5",
            "--trainer.callbacks.mode=max",
            "--trainer.callbacks.monitor=Val/AP",
            "--trainer.callbacks+=ModelCheckpoint",
            "--trainer.callbacks.dirpath=/pvc/logs/biomedbert/666-biomedbert-none",
            "--trainer.callbacks.filename=checkpoint",
            "--trainer.callbacks.save_top_k=1",
            "--trainer.callbacks.monitor=Val/AP",
            "--trainer.num_sanity_val_steps=1",
            "--trainer.max_epochs=5",
            "--data.num_workers=8",
            "--data.eval_batch_size=8",
            "--data.batch_size=8",
            "--data.tokenizer=microsoft/BiomedNLP-biomedbert-base-uncased-abstract-fulltext",
            "--model.encoder_model_name=microsoft/BiomedNLP-biomedbert-base-uncased-abstract-fulltext",
            "--model.num_classes=20",
            "--model.warmup_steps=100",    
            "--model.device=cuda",
            "--model.eval_treshold=0.5",
            "--model.lr=2e-05",
            "--model.hidden_dim=768",
            "--seed_everything=666",
            "--data.dataset_path=/pvc/data/processed",
            "--data.dataset_stem=-00000-of-00001_ne_redacted.parquet",
            "--data.redaction_type=None",
          ]
          env:
            - name: LANG
              value: 'C.UTF-8'
            - name: TOKENIZERS_PARALLELISM
              value: 'true'
            - name: NCCL_DEBUG
              value: 'INFO'
            - name: HF_HOME
              value: "/pvc/huggingface_cache"
          resources:
            requests:
              cpu: "1"
            limits:
              nvidia.com/gpu: "1"
              memory: 15Gi
          volumeMounts:
            - name: text-redact-pvc
              mountPath: /pvc
            - name: dshm
              mountPath: /dev/shm
      nodeSelector:
        #kubernetes.io/hostname: cl-worker24
        gpu: a100
      volumes:
        - name: text-redact-pvc
          persistentVolumeClaim:
            claimName: text-redact-pvc
        - name: dshm
          emptyDir:
            medium: Memory
      imagePullSecrets:
        - name: private-registry-auth
      restartPolicy: Never