apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-redact-tensorboard
  labels:
    app: text-redact-tensorboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: text-redact-tensorboard
  template:
    metadata:
      labels:
        app: text-redact-tensorboard
    spec:
      containers:
        - name: text-redact-tensorboard
          image: registry.datexis.com/pgrundmann/tensorboard
          command: ["tensorboard", "--logdir=/pvc/logs/", "--host", "0.0.0.0"]
          ports:
          -  containerPort: 6006
          resources:
            requests:
              cpu: "0.01"
            limits:
              memory: "4G"
          volumeMounts:
            - name: text-redact-pvc
              mountPath: /pvc
      volumes:
        - name: text-redact-pvc
          persistentVolumeClaim:
            claimName: text-redact-pvc
      imagePullSecrets:
        - name: private-registry-auth
